service: gym-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage,'dev'}
  environment:
    DB_PROVIDER: ${self:custom.env.DB_PROVIDER.${self:provider.stage}}
    EVENT_PROVIDER: ${self:custom.env.EVENT_PROVIDER.${self:provider.stage}}
    REDIS_HOST: ${ssm:/gym-api/${self:provider.stage}/redis/host}
    REDIS_PORT: ${ssm:/gym-api/${self:provider.stage}/redis/port}
    REDIS_PASSWORD: ${ssm:/gym-api/${self:provider.stage}/redis/password}
    EVENTOS_TABLE: eventos
    IS_OFFLINE: ${env:IS_OFFLINE, 'false'}
    
    SNS_TOPIC_ARN:
      Ref: ClienteRegistradoTopic # ARN del SNS Topic inyectado automáticamente por CloudFormation (cliente-registrado-topic) cuando se despliega la infraestructura (serverless deploy)


  iam:  # Permisos IAM para las Lambdas puedan interactuar con DynamoDB y SNS
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem  # permite crear/guardar registros en DynamoDB
            - dynamodb:Query    # permite consultar datos en DynamoDB
          Resource: "*"
        - Effect: Allow
          Action:
            - sns:Publish       # permite publicar mensajes en SNS
          Resource:
            - Ref: ClienteRegistradoTopic # restringido SOLO a este topic (cliente-registrado-topic)
        - Effect: Allow
          Action:
            - ssm:GetParameter  # permite leer parameter store
            - ssm:GetParameters
          Resource: "*"

custom:
  env:
    DB_PROVIDER:
      local: redis
      dev: redis
      prod: postgres
    EVENT_PROVIDER:
      local: console
      dev: sns
      prod: sns
    REDIS_HOST:
      local: ${env:REDIS_HOST, 'localhost'}
      dev: ${ssm:/aws/reference/secretsmanager/gym-api/dev/redis:host, ''}
    REDIS_PORT:
      local: ${env:REDIS_PORT, '6379'}
      dev: ${ssm:/aws/reference/secretsmanager/gym-api/dev/redis:port, ''}
    REDIS_PASSWORD:
      local: ${env:REDIS_PASSWORD, ''}
      dev: ${ssm:/aws/reference/secretsmanager/gym-api/dev/redis:password, ''}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

package:
  patterns:
    - src/**

functions: ${file(./config/serverless/functions.local.yaml)}
resources: ${file(./config/serverless/resources.local.yaml)}
# resources:
#   Resources:
#     EventosTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: eventos
#         AttributeDefinitions:
#           - AttributeName: userId
#             AttributeType: S
#           - AttributeName: timestamp
#             AttributeType: S
#         KeySchema:
#           - AttributeName: userId
#             KeyType: HASH
#           - AttributeName: timestamp
#             KeyType: RANGE
#         BillingMode: PAY_PER_REQUEST