# Este archivo define:
# - Lambdas HTTP (sincrónicas → API Gateway)
# - Lambdas asincrónicas (event-driven → SNS, SQS)

getClientes:
  handler: src/cliente/infrastructure/handlers/obtener-clientes.handler
  events:
    - httpApi:
        path: /clientes
        method: get

getCliente:
  handler: src/cliente/infrastructure/handlers/obtener-cliente.handler
  events:
    - httpApi:
        path: /clientes/{id}
        method: get

createCliente:
  handler: src/cliente/infrastructure/handlers/agregar-cliente.handler
  events:
    - httpApi:
        path: /clientes
        method: post

login:
    handler: src/auth/infrastructure/handlers/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: post



registrarEvento:
  handler: src/evento/infrastructure/handlers/registrar-evento.handler
  events:
    - httpApi:
        path: /eventos
        method: post

obtenerEventos:
  handler: src/evento/infrastructure/handlers/obtener-eventos.handler
  events:
    - httpApi:
        path: /eventos
        method: get

# Funciones asincrónicas (event-driven)

clienteRegistrado:  # reactivo: reacciona automáticamente a eventos (ej: envía email con SES)
  handler: src/notifications/infrastructure/handlers/cliente-registrado.handler
  events:
    - sns:
        arn:
          Ref: ClienteRegistradoTopic
        topicName: cliente-registrado-topic